// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecretSantaBackend.Data;

#nullable disable

namespace SecretSantaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205130646_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecretSantaBackend.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GiverId")
                        .HasColumnType("integer");

                    b.Property<int>("ListId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GiverId");

                    b.HasIndex("ListId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.SecretSantaList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UnpairedEmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UnpairedEmployeeId");

                    b.ToTable("SecretSantaLists");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.Pair", b =>
                {
                    b.HasOne("SecretSantaBackend.Models.Employee", "Giver")
                        .WithMany("DrawnPair")
                        .HasForeignKey("GiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SecretSantaBackend.Models.SecretSantaList", "List")
                        .WithMany("Pairs")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecretSantaBackend.Models.Employee", "Receiver")
                        .WithMany("GiverPair")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Giver");

                    b.Navigation("List");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.SecretSantaList", b =>
                {
                    b.HasOne("SecretSantaBackend.Models.Employee", "UnpairedEmployee")
                        .WithMany()
                        .HasForeignKey("UnpairedEmployeeId");

                    b.Navigation("UnpairedEmployee");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.Employee", b =>
                {
                    b.Navigation("DrawnPair");

                    b.Navigation("GiverPair");
                });

            modelBuilder.Entity("SecretSantaBackend.Models.SecretSantaList", b =>
                {
                    b.Navigation("Pairs");
                });
#pragma warning restore 612, 618
        }
    }
}
